### PR TITLE
Initial code import

### PR DESCRIPTION
**Pull request by tmnd1991**

### CODE REVIEW

**Comment by andrea-rockt** [comment]
Code LGTM

Should we choose a license?

Also what about continuous integration?

**Comment by tmnd1991** [comment]
What about Apache 2.0 like Darwin?

**Comment by tmnd1991** [comment]
As per CI, I will setup travis!

**Comment by tmnd1991** [comment]
Can you @andrea-rockt or @agile-lab enable travis for this repo?
https://travis-ci.org/organizations/agile-lab-dev/repositories

**Comment by andrea-rockt** [comment]
Apache license should be fine

**Pull request merged**
